spring:
  application:
    name: people
  profiles:
    active: ${SPRING_PROFILE:local}

grpc:
  server:
    port: 9090

client:
  typicode:
    base-url: https://jsonplaceholder.typicode.com

logging:
  level:
    root: INFO
    org.people: DEBUG
    io.grpc: INFO
    net.devh: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
